./autogen.sh --prefix=/usr     \
             --sysconfdir=/etc \
             --localstatedir=/var \
             --libexecdir=/usr/lib/cinnamon \
             --disable-static \
             $OPTS           &&

default_make

