OPTS+=" --disable-static      \
        --enable-exchange     \
        --enable-facebook     \
        --enable-flickr       \
        --enable-google       \
        --enable-imap-smtp    \
        --enable-owncloud     \
        --enable-windows-live \
        --enable-media-server"

default_build
