OPTS+=" --enable-exchange      \
        --enable-facebook      \
        --enable-flickr        \
        --enable-google        \
        --enable-imap-smtp     \
        --enable-owncloud      \
        --enable-windows-live  \
        --enable-media-server" &&

OPTS+=" --libexecdir=/usr/lib/$MODULE" &&

default_build
