OPTS+=" --enable-ipv6 \
        --enable-gdm-session \
        --disable-static \
        --without-plymouth \
        --without-console-kit \
        --without-tcp-wrappers \
        --disable-schemas-compile" &&

OPTS+=" --libexecdir=/usr/lib/gdm" &&

default_build
