OPTS+=" --disable-icon-update \
        --disable-desktop-update \
        --disable-schemas-compile" &&

./configure --prefix=/usr \
            --libexec=/usr/lib \
            $OPTS &&

default_make
