OPTS+=" --disable-static \
        --disable-ifcfg-rh \
        --disable-ifupdown \
        --disable-lto \
        --disable-more-logging \
        --disable-more-warnings \
        --with-libnm_glib \
        --with-nmtui \
        --with-nmcli"

default_build
