OPTS+=" --prefix=/usr \
        --libdir=/usr/lib \
        --sysconfdir=/etc \
        -D with-polkit=true \
        -D with-bluetooth=true \
        -D with-desktop-icons=none"

default_meson_build
