sedit '34i typedef unsigned long z_crc_t;' src/crypt-util.c &&

export LANG='en_US.UTF-8'

OPTS+=" -D docbook=false \
        -D gtk_doc=false \
        -D admin_group=wheel \
        -D introspection=true \
        -D tests=false"

default_meson_build
