OPTS+=" --disable-static \
        --disable-schemas-compile \
        --with-root-certs=/etc/ssl/certs \ 
        --with-pam-dir=/usr/lib/security" &&

OPTS+=" --libexecdir=/usr/lib/$MODULE" &&

default_build
