rm -f /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache &&

# others=enabled is for the xpm loader and few others, needed by gkrellm
OPTS+=" -Dothers=enabled  \
        -Dinstalled_tests=false \
        -Dgtk_doc=false \
        -Dintrospection=enabled"

default_meson_build
