autoreconf -fvi &&

OPTS+=" --enable-defaults-service  \
        --disable-static \
        --disable-gtk \
        --enable-gsettings-backend \
        --disable-gtk-doc-html \
        --disable-orbit"

default_build
