export HAVE_VALGRIND_TRUE='#'
export HAVE_VALGRIND_FALSE=''
export CFLAGS=" -Wno-error"

OPTS=" --disable-dumper --disable-tests --disable-static --with-gtk=3 --enable-gtk-doc-html=no"

NOCONFIGURE=1 ./autogen.sh &&

default_build
